name: bmi_app
description: A new Flutter application.
version: 1.0.0+1
authors:
  - Shyn <thaison.coderstokyo@gmail.com>
environment:
  sdk: '>=2.1.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  flutter_svg: ^0.15.0
  flutter_bloc: ^3.1.0
  provider: ^4.0.2
  injectable: ^3.1.0
  http: ^0.12.0+3
  firebase_auth:
  firebase_database:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Medium.ttf
        - asset: assets/fonts/Roboto-Italic.ttf
          style: italic
    # - family: Trajan Pro
    #   fonts:
    #     - asset: fonts/TrajanPro.ttf
    #     - asset: fonts/TrajanPro_Bold.ttf
    #       weight: 700
